# yaml =  yet another markuo language
# aint markup language

on : push
jobs : 
    first-job:
      runs-on : windows-latest
      steps :
        - run : node --version
        - run : npm --version
        - used : actions/checkout@v3
        - run : node index.js
